# Generated by Django 5.2.4 on 2025-07-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_delete',
            field=models.BooleanField(default=0, verbose_name='Is Deleted'),
        ),
    ]
