# Generated by Django 5.2.4 on 2025-07-12 22:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format +910000000000. Up to 13 digits allowed.', regex='^\\+?\\d{9,13}$')]),
        ),
    ]
