# Generated by Django 5.2.4 on 2025-07-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productcolor_delete_color_alter_product_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
