# Generated by Django 5.2.4 on 2025-07-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productimage',
            name='unique_primary_image_per_product',
        ),
        migrations.RemoveIndex(
            model_name='productimage',
            name='product_ima_product_55415d_idx',
        ),
    ]
